In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
iris
type(iris)

sklearn.utils.Bunch

In [4]:
iris.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
print(iris["target_names"])
print(iris.target_names)

['setosa' 'versicolor' 'virginica']
['setosa' 'versicolor' 'virginica']


In [12]:
n_samples, n_features = iris.data.shape

In [9]:
print("Number of samples:",n_samples)
print("Number of features:",n_features)

Number of samples: 150
Number of features: 4


In [10]:
print(iris.data[0])

[5.1 3.5 1.4 0.2]


In [13]:
iris.data[[12,20,89,114]]

array([[4.8, 3. , 1.4, 0.1],
       [5.4, 3.4, 1.7, 0.2],
       [5.5, 2.5, 4. , 1.3],
       [5.8, 2.8, 5.1, 2.4]])

In [14]:
import numpy as np
np.bincount(iris.target)

array([50, 50, 50])

In [15]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']
